[package]
name = "axvm-sdk-example-test"
version = "0.1.0"
edition = "2021"

[dependencies]
axvm = { path = "../../afs-prototype/crates/toolchain/axvm", default-features = false }
serde = { version = "1.0.200", default-features = false, features = ["derive"] }
