name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Clippy
      run: cargo clippy --all-targets -- -D warnings
    - name: Build
      run: cargo build --verbose --no-default-features 
    - name: Run tests
      run: cargo test --verbose 
  test-no-std:
    name: test no_std
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly-2026-01-18
        with:
          components: rust-src
      - name: Checkout openvm
        run: git clone --depth=1 --branch=develop-v2.1.0-rv64 https://github.com/openvm-org/openvm.git /tmp/openvm
      - run: RUSTFLAGS="-Z unstable-options --cfg openvm_intrinsics" RUST_TARGET_PATH=/tmp/openvm/crates/toolchain/build cargo check -Z build-std=core,alloc --target riscv64im-openvm-none-elf --no-default-features