name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  OPENVM_FAST_TEST: "1"

jobs:
  test:
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=64cpu-linux-arm64
      - extras=s3-cache

    steps:
      - uses: runs-on/action@v1
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@nextest

      - name: Run tests
        run: |
          rustup install nightly-2025-02-14
          rustup component add rust-src --toolchain nightly-2025-02-14
          cargo nextest run --release
